GOOGLE_CLIENT_ID: "696252052176-cmp61clmde8gd0cp0c40q5pkl1jouhqn.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "SZoA8eKy2dDM8RtWZdYhikhO"
SENDGRID_USERNAME: "my_potholeapp"
SENDGRID_PASSWORD: "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"
